### ISSUE TITLE
Specifying a @context in json-schema

### ISSUE THREAD

**Issue by ioggstream** [w3c/wot-thing-description#1233]
## Question

If we specify a json-schema like the one in  https://www.w3.org/2019/wot/json-schema#example-5-schema-with-context-annotation

```
{
    "@context": {
        ...,
        "jsonld": "http://www.w3.org/ns/json-ld#"
    }
    "jsonld:context": "http://schema.org",
    "type": "object",
    "description": "Schema of a commercial product with GTIN and manufacturer",
    "properties" : {
        "gtin14": { "type": "string" },
        "manufacturer": { "type": "string" }
    }
}
```

doesn't seem to me a valid json-schema.

A cleaner way to do it could be to just express the context in a given property (in yaml syntax).

```yaml
type: object
description: "Schema of a commercial product with GTIN and manufacturer"
properties:
  gtin: { "type": "string" }
  manufacturer: { "type": "string" },
  "@context":
    const:
      "@vocab": http://schema.org/
```

cc: @relu91

**Comment by egekorkan** [comment]
I am not sure if I understand this correctly, the goal is not to say that this whole thing is a JSON Schema but that you can extend a JSON Schema with these annotations. `@context` and `jsonld:context` are not (validation) keywords to be picked up by a JSON Schema parser. The cleaner way is wrong in my point of view. The actual clean way would be to treat them as JSON Schema vocabulary items that are introduced in the recent JSON Schema version

**Comment by ioggstream** [comment]
Hi @egekorkan! The goal is to extend json-schema with annotations referencing a jsonld context.

In  [Example 6](https://www.w3.org/2019/wot/json-schema#ctx-ref) we see a json-ld object

```
{
    "@context": "http://schema.org",
    "name": "some manufactured product",
    "gtin14": "0 00 12345 60001 2",
    "manufacturer": "http://comapny.example.com"
}
```

where the `@context` property is not defined in the above json-schema. 

Since a json-schema best practice suggests to use `additionalProperties: false` and add a list of required fields (for example, [the above json schema](https://www.w3.org/2019/wot/json-schema#example-schema-with-context-annotation) validates almost any object, including  `{"user": "foo", "password": "bar" }`.

This means that, in practice, if you need to validate [Example6](https://www.w3.org/2019/wot/json-schema#ctx-ref)  you will probably need to add the `@context` property  thus making it a validation keyword (but you may don't want to have such a strict validation though).

```
type: object
description: "Schema of a commercial product with GTIN and manufacturer"
additionalProperties: false
required:
- gtin
- manufacturer
properties:
  gtin: { "type": "string" }
  manufacturer: { "type": "string" },
  "@context":
    const:
      "@vocab": http://schema.org/
```

About Vocabulary Items, they are probably a suitable solution: I'll have a look!
