### ISSUE TITLE
update tool-analysis.md re SOML

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/wot-thing-description#1982]
Hi @mahdanoura!

I was pointed to https://github.com/w3c/wot-thing-description/blob/main/toolchain/tool-analysis.md by egekorkan.
I guess your tool selection is completed (I see elsewhere "STTL" and that's a nice tool; I use its newer incarnation SPARLQ Generate).
So this issue is probably unimportant and petty.

But I have a couple of clarifications about SOML (that's https://platform.ontotext.com/semantic-objects/soml/index.html, right?)
- "Language" is java
- "`Type/Type[]` support": we have it, that's `max: 1` (which is default) vs any bigger `max`. This distinction is crucial for GraphQL
- "Unknown object keys": what is that?
- "SHACL Shapes Generation": we have that. The SOML model is used to generate GraphQL mutations, but also SHACL shapes that are used if you load RDF data in bulk (not through mutations)
- "Diagram Generation": see 
  - https://twitter.com/valexiev1/status/1648342188558786562 
  - https://bsdd.ontotext.com/, the 3 diagrams at "Refactored GraphQL schema visualization with Voyager..."

**Comment by egekorkan** [comment]
> "Unknown object keys": what is that?

That is the case where you have an object but the information model doesn't define what they should be. In TDs, you have properties, actions and events objects but each TD picks the terms that suits them. So in the example below, `status` property can be different in each TD:
```js
"properties": {
        "status": {
            "type": "string",
            "forms": [{"href": "https://mylamp.example.com/status"}]
        }
    },
```

**Comment by VladimirAlexiev** [comment]
@egekorkan then SOML supports this: https://platform.ontotext.com/semantic-objects/soml/properties.html
> (you can) Change `rdfProp`. This allows different predicates to be queried in a subclass. 

As an example, you can have this:
```yaml
objects:
  Thing:
    props:
      status:
  MyThing:
    inherits: Thing
    props:
      status: {rdfProp: https://mything.example.com/status}
  YourThing:
    inherits: Thing
    props:
      status: {rdfProp: https://yourthing.example.com/status}
```
Then you can use this GraphQL query
```graphql
query ThingsWithStatus {
  thing {status}
}
```
